import React from "react";
import { Radio, Icon } from "antd";
import { NO_OP } from "../utils";

const MyIcon = Icon.createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_1451714_unqkw1i8v4s.js" // generated by iconfont.cn
});

const defaultProps = {
  size: "large",
  value: 0,
  onChange: NO_OP
};
const RadioGroup = React.memo(function RadioGroup(props) {
  const { size, value, onChange } = { ...defaultProps, ...props };
  const onChanged = event => {
    const value = event.target.value;
    onChange(value);
  };
  return (
    <Radio.Group
      size={size}
      value={value}
      buttonStyle="solid"
      name="oscillator-type"
      onChange={onChanged}
    >
      <Radio.Button value="sine">
        <MyIcon type="iconwave-sine" />
      </Radio.Button>
      <Radio.Button value="square">
        <MyIcon type="iconwave-square" />
      </Radio.Button>
      <Radio.Button value="triangle">
        <MyIcon type="iconwave-triangle" />
      </Radio.Button>
      <Radio.Button value="sawtooth">
        <MyIcon type="iconwave1" />
      </Radio.Button>
    </Radio.Group>
  );
});

export default RadioGroup;
