import React from "react";
import { Radio, Icon } from "antd";

const MyIcon = Icon.createFromIconfontCN({
  scriptUrl: "//at.alicdn.com/t/font_1451714_unqkw1i8v4s.js" // generated by iconfont.cn
});

function RadioGroup({ value, onChange }) {
  return (
    <Radio.Group
      value={value}
      buttonStyle="solid"
      name="oscillator-type"
      onChange={onChange}
    >
      <Radio.Button value="sine">
        <MyIcon type="iconwave-sine" />
      </Radio.Button>
      <Radio.Button value="square">
        <MyIcon type="iconwave-square" />
      </Radio.Button>
      <Radio.Button value="triangle">
        <MyIcon type="iconwave-triangle" />
      </Radio.Button>
      <Radio.Button value="sawtooth">
        <MyIcon type="iconwave1" />
      </Radio.Button>
    </Radio.Group>
  );
}

export default RadioGroup;
